


services:
  - type: static
    name: tumor-trace-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - path: /assets/*
        type: static
      - path: /*
        destination: /index.html

        